# Generated by Django 3.2.7 on 2021-10-03 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(default=datetime.date(2021, 11, 1)),
        ),
    ]
