# Generated by Django 3.2.7 on 2021-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_remove_project_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doc',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(default=''),
        ),
    ]
