# Generated by Django 3.2.7 on 2021-10-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20211003_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doc',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(blank=True, default=''),
        ),
    ]
