# Generated by Django 3.2.7 on 2021-10-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20211003_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
